Implement mentee application windows shopping feature
sef-global/scholarx-frontend-v1 pull request #111
Opened 2021-04-18 07:28 UTC by Gravewalker666

## Purpose

The purpose of this PR is to fix #94, fix #109, fix #103 
- Prompt users with a modal to sign in where sign-in is necessary.
- Prevent users from accessing unauthorised pages.
- Replace the avatar icon with the profile picture in the dashboard navigation bar.

## Goals

To implement the windows shopping feature and prevent users from accessing unauthorised pages.

## Approach

#### Window Shopping feature 
- Created a new `LogInModal` component high up in the component hierarchy(`/src`)
- Provided public users with a button to click on and get into the mentor list 
- Configured the above-mentioned modal to pop up when the user clicks on a mentor

https://user-images.githubusercontent.com/45477334/115137769-acf72e00-a045-11eb-846e-d91b132845b8.mp4

#### Preventing users from accessing unauthorised pages
- Used the above-defined `LogInModal` and prompted the non-logged in users with the option to sign in to continue
- Made the `LogInModal` un-cancellable 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/115137529-4cb3bc80-a044-11eb-8218-e03a4871dfab.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/115137545-5b01d880-a044-11eb-9808-079a765ec2d6.png">

### Replace the avatar icon with the profile picture
- Removed the avatar icon and replace it with `src={user?.imageUrl}`
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/115137507-30b01b00-a044-11eb-9d39-8b4f4944a0e2.png">

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
- webpack dev server
- Safari
- macOS Big Sur 

## Learning

2021-04-18 07:46 UTC, anjula-sack requested changes
Awesome! @Gravewalker666

2021-04-18 07:46 UTC, anjula-sack commented on src/components /LogInModal/index.tsx
> +      'http://localhost:8080/oauth2/authorization/linkedin';
Let's create another variable to store the sign in url

2021-04-18 07:46 UTC, anjula-sack commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  </Card>
This is the mentor card right? It's better to create another component for this.

2021-04-18 07:47 UTC, anjula-sack commented on src/components /LogInModal/index.tsx
> +      'http://localhost:8080/oauth2/authorization/linkedin';
BTW, We are going to pass the redirect location URL right?

2021-04-18 11:19 UTC, Gravewalker666 commented on src/components /LogInModal/index.tsx
> +      'http://localhost:8080/oauth2/authorization/linkedin';
> Let's create another variable to store the sign-in URL

Sure, On it

> BTW, We are going to pass the redirect location URL right?

Let's do that part after getting this PR merged, we have to handle the redirection in some other places as well so let's work on the whole bunch together in a different PR

2021-04-18 11:20 UTC, Gravewalker666 commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  </Card>
Yeah, that's better, thanks for the suggestion.

2021-04-18 11:45 UTC, Gravewalker666 commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  </Card>
Resolved with the commit [a872f99](https://github.com/sef-global/scholarx-frontend/pull/111/commits/a872f992675be8cf3b0e1e9c556bc63c704161a8)

Please review =)

2021-04-18 11:45 UTC, Gravewalker666 commented on src/components /LogInModal/index.tsx
> +      'http://localhost:8080/oauth2/authorization/linkedin';
Resolved with the commit [a872f99](https://github.com/sef-global/scholarx-frontend/pull/111/commits/a872f992675be8cf3b0e1e9c556bc63c704161a8)

Please review =)

2021-04-18 12:27 UTC, anjula-sack commented
The build is failing and why is there a change in the `package-lock.json`?

2021-04-18 13:19 UTC, anjula-sack approved these changes
Good job! @Gravewalker666

2021-04-18 14:53 UTC, merged

2021-06-27 14:47 UTC, Gravewalker666 commented on src/components /LogInModal/index.tsx
> +      'http://localhost:8080/oauth2/authorization/linkedin';
b04eb4d