Create change program state UI
sef-global/scholarx-frontend-v1 pull request #13
Opened 2020-10-02 16:45 UTC by Gravewalker666

## Purpose

The purpose of this PR is to fix #5 

## Goals

To create manage program user interface with the functionality to change the state of the program

## Approach
Implemented the UI using ant design components

## Screenshots
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/94948063-55a3cd00-04fc-11eb-805d-b376af5efc0c.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/94948102-618f8f00-04fc-11eb-84b1-45a90ec00ae0.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/94948122-6d7b5100-04fc-11eb-882d-9d00feb0f717.png">

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
 Browser: Google Chrome, Safari
Server: webpack dev server
Os: macOS 10.15.3

2020-10-03 14:16 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +              disabled={currentStep >= 5}
We can use `programStates.length - 1` to make it dynamic

2020-10-03 14:16 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +              percent={Math.round((currentStep * 100) / 6)}
Let's use `programStates.length`

2020-10-03 14:17 UTC, anjula-sack requested changes
Make the request changes. :)

2020-10-03 16:08 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +              percent={Math.round((currentStep * 100) / 6)}
Sure!

2020-10-03 16:09 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +              disabled={currentStep >= 5}
Good catch! I will change that

2020-10-03 16:14 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +              disabled={currentStep >= 5}
Resolved with commit https://github.com/sef-global/scholarx-frontend/pull/13/commits/a8d2d216eafa36089c612a8f7e568d07ebad8899. Please review.

2020-10-03 16:14 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +              percent={Math.round((currentStep * 100) / 6)}
Resolved with commit https://github.com/sef-global/scholarx-frontend/pull/13/commits/a8d2d216eafa36089c612a8f7e568d07ebad8899. Please Review.

2020-10-04 11:27 UTC, anjula-sack submitted a review, later dismissed
Amazing work! 😍 @Gravewalker666

2020-10-04 15:47 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +            {/* TODO: Use a context to keep the specific program of the dashboard
Let's change the comment

2020-10-04 15:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +const ChangeState = () => {
```suggestion
function ChangeState(){
```

Just to improve the readability

2020-10-04 15:50 UTC, jayasanka-sack commented on src/scenes/Dashboard/index.tsx
> +          }}
Let's avoid using inline css

2020-10-04 15:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/index.tsx
> +                path="/dashboard/edit_state"
I think better to use - instead _ in urls. 

Major platforms use this practice because it's hard to identify underscores when the url's get underlined automatically when shared on somewhere

2020-10-06 06:25 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +            {/* TODO: Use a context to keep the specific program of the dashboard
Sure!

2020-10-06 06:26 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +const ChangeState = () => {
I'm on it!

2020-10-06 06:26 UTC, Gravewalker666 commented on src/scenes/Dashboard/index.tsx
> +                path="/dashboard/edit_state"
Yeah, totally.

2020-10-06 06:26 UTC, Gravewalker666 commented on src/scenes/Dashboard/index.tsx
> +          }}
Ahh.. yes. sure!!

2020-10-06 06:38 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +            {/* TODO: Use a context to keep the specific program of the dashboard
Resolved with commit https://github.com/sef-global/scholarx-frontend/pull/13/commits/b3f5828504720c39c8fe49b514b6e216c682eacb. Please review it again.

2020-10-06 06:38 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ChangeState/index.tsx
> +const ChangeState = () => {
Resolved with commit https://github.com/sef-global/scholarx-frontend/pull/13/commits/b3f5828504720c39c8fe49b514b6e216c682eacb. Please review it again.

2020-10-06 06:38 UTC, Gravewalker666 commented on src/scenes/Dashboard/index.tsx
> +          }}
Resolved with commit https://github.com/sef-global/scholarx-frontend/pull/13/commits/b3f5828504720c39c8fe49b514b6e216c682eacb. Please review it again.

2020-10-06 06:38 UTC, Gravewalker666 commented on src/scenes/Dashboard/index.tsx
> +                path="/dashboard/edit_state"
Resolved with commit https://github.com/sef-global/scholarx-frontend/pull/13/commits/b3f5828504720c39c8fe49b514b6e216c682eacb. Please review it again.

2020-10-12 02:53 UTC, anjula-sack approved these changes
Awesome! 👏 @Gravewalker666

2020-10-12 04:01 UTC, Gimhan-minion approved these changes
Looks Awesome @Gravewalker666 :100:

2020-10-13 09:52 UTC, jayasanka-sack approved these changes
Thanks @Gravewalker666 !!

2020-10-13 09:52 UTC, merged