Add two buttons to go to home or edit after submission #90 (Draft)
sef-global/scholarx-frontend-v1 pull request #130
Opened 2021-05-09 08:03 UTC by kumuditha-udayanga

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-05-09 08:17 UTC, anjula-sack commented on src/scenes/Home/components/ResultScreen/index.tsx
> +            key="buy"
let's change the key

2021-05-09 08:24 UTC, kumuditha-udayanga commented on src/scenes/Home/components/ResultScreen/index.tsx
> +            key="buy"
Sure

2021-05-09 14:22 UTC, anjula-sack commented on src/scenes/Home/components/ResultScreen/index.tsx
> +        subTitle=""
Let's remove this

2021-05-09 14:23 UTC, anjula-sack commented on src/scenes/Home/components/ResultScreen/index.tsx
> +  const id = props.programId;
`const {programId} = props` let's use it like this

2021-05-09 14:23 UTC, anjula-sack commented on src/scenes/Home/components/ResultScreen/styles.css
> +}
EOL

2021-05-09 14:24 UTC, anjula-sack requested changes
Good job! @kumuditha-udayanga Can we add the result inside a card?

2021-05-10 07:07 UTC, kumuditha-udayanga commented
> Good job! @kumuditha-udayanga Can we add the result inside a card?
Thank you, sure I'll add it inside a card.

2021-05-10 08:08 UTC, anjula-sack approved these changes
Thank you! @kumuditha-udayanga

2021-05-10 08:08 UTC, merged