Edit apply as a mentor UI and edit application UI to display dynamic questions
sef-global/scholarx-frontend-v1 pull request #142
Opened 2021-05-15 07:55 UTC by NethmiRodrigo

## Purpose

The purpose of this PR is to fix #127 

## Goals
- Enhance the "apply as a mentor" UI so that it displays questions dynamically fetched from the backend
- Change the "edit application" UI to fetch previously submitted answers from the backend 

## Approach
Used the corresponding endpoints to fetch questions when applying and previous responses of the respective mentor when editing

## Screenshots
**This will be subjected to change**
![image](https://user-images.githubusercontent.com/34070216/118352707-73500f00-b580-11eb-844e-7f8ab9700b72.png)

**Currently working on making it look like below**
![image](https://user-images.githubusercontent.com/34070216/118352769-d3df4c00-b580-11eb-8b4b-88e6e4c9452a.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
Google Chrome
Windows 10
Node v12.16.1

2021-05-15 14:35 UTC, NethmiRodrigo commented
**The UI has been updated to look like the following**
![image](https://user-images.githubusercontent.com/34070216/118365052-baf28d00-b5b8-11eb-805d-00094c46e745.png)

2021-05-16 04:02 UTC, anjula-sack requested changes
Good job! @NethmiRodrigo Small changes are requested.

2021-05-16 04:02 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorApplication/index.tsx
> +  const [answers, setAnswers] = useState<any[]>([]);
Let's try not to use `any` type.

2021-05-16 04:02 UTC, anjula-sack commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +          });
Let's move this to seperate function.

2021-05-16 04:02 UTC, anjula-sack commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +    let error: any;
Try to find the type of the error instead of using `any` type

2021-05-16 04:02 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorApplication/index.tsx
> +    let error: any = null;
Same here

2021-05-16 05:45 UTC, NethmiRodrigo commented on src/scenes/Home/scenes/MentorApplication/index.tsx
> +  const [answers, setAnswers] = useState<any[]>([]);
I used any type because this is a custom data structure I made to save just the answers and question id. I wasn't sure if we should make an interface for data types that we just used in one component on the front end

2021-05-16 11:32 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorApplication/index.tsx
> +  const [answers, setAnswers] = useState<any[]>([]);
You can create an interface file in the `MentorApplication` directory if it's gonna be used only inside that component.  Let's create an interface for that. 

![image](https://user-images.githubusercontent.com/43912578/118395506-64448c00-b668-11eb-93ca-65c7d117752f.png)

2021-05-22 10:27 UTC, NethmiRodrigo commented
> Good job! @NethmiRodrigo Small changes are requested.

Sorry about the delay. Fixed changes as requested in commit 2c5effc. Please review :)

2021-05-22 15:20 UTC, anjula-sack requested changes

2021-05-22 15:20 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorApplication/index.tsx
> +  const apply = async (values: any) => {
Don't use `any` type

2021-05-22 15:20 UTC, anjula-sack commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +  const apply = async (values: any) => {
What is the reason for using `any` type

2021-05-22 15:20 UTC, anjula-sack commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +    const response: AxiosResponse<any> = await updateApplication(
Same here

2021-05-22 15:50 UTC, Gravewalker666 requested changes

2021-05-22 15:50 UTC, Gravewalker666 commented on src/util/program-services.ts
> +    );
Let's take the `QuestionCategory` as a parameter and put it in the api URL so that we can use the same function to get mentee programs.

2021-05-22 15:50 UTC, Gravewalker666 commented on src/util/program-services.ts
> +    });
Shouldn't this be 'Something went wrong when fetching the questions' ?

2021-05-22 16:26 UTC, NethmiRodrigo commented on src/scenes/Home/scenes/MentorApplication/index.tsx
> +  const apply = async (values: any) => {
These are the values that the antd Form component passes in and it was used like this throughout so that's why I left is as any

2021-05-22 16:27 UTC, NethmiRodrigo commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +    const response: AxiosResponse<any> = await updateApplication(
Only the AxiosResponse body's type is known so what should I put here?

2021-05-22 16:28 UTC, NethmiRodrigo commented on src/util/program-services.ts
> +    );
Good eye @Gravewalker666! Will do :)

2021-05-22 16:28 UTC, NethmiRodrigo commented on src/util/program-services.ts
> +    });
Yes lol my bad xD. Will fix

2021-05-23 04:50 UTC, NethmiRodrigo commented
Fixed as requested @Gravewalker666 @anjula-sack :)

2021-05-23 05:46 UTC, Gravewalker666 commented on src/util/program-services.ts
> +    });
You have missed one here xd

2021-05-24 14:28 UTC, NethmiRodrigo commented on src/util/program-services.ts
> +    });
@Gravewalker666 lol xD fixed it :)

2021-05-24 14:39 UTC, Gravewalker666 approved these changes
Great work @NethmiRodrigo 
Thank you very much for getting this done

2021-05-24 14:51 UTC, NethmiRodrigo commented
> Great work @NethmiRodrigo
> Thank you very much for getting this done

My pleasure and sorry about the delay 😄

2021-05-25 12:13 UTC, merged