Implement new admin UI to add and edit mentee questions
sef-global/scholarx-frontend-v1 pull request #146
Opened 2021-05-15 17:29 UTC by YaiyaSam

## Purpose

The purpose of this PR is to fix #145

## Goals

To create a new admin UI to add and edit mentee questions

## Approach

## Screenshots

![image](https://user-images.githubusercontent.com/72991092/118372777-d5386500-b5d0-11eb-8d6a-bb9491d4ef38.png)
![image](https://user-images.githubusercontent.com/72991092/118372790-e6817180-b5d0-11eb-90e4-f829a408478d.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 
Google Chrome
Webpack dev server
Windows 10

## Learning

2021-05-16 04:20 UTC, Gravewalker666 requested changes
Great Job @YaiyaSam 
Requested some minor changes

2021-05-16 04:20 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/MenteeQuestions/components/AddQuestions/index.tsx
> +                placeholder="Ex: What is your highest level of education?"
Let's change the placeholder text to something more fitting like "Please let us know your top areas of interest (maximum 5 areas)"

2021-05-16 04:20 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/MenteeQuestions/components/EditQuestions/index.tsx
> +    setIsLoading(true);
We don't have to set `isLoading` to `true` twice. Remove the second one.

2021-05-16 04:20 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/MenteeQuestions/styles.css
> +}
Let's import these styles from the previous CSS file without creating a new one. We may even have to move that styles file up the hierarchy because it is used in two components.

2021-05-16 07:11 UTC, YaiyaSam commented
@Gravewalker666 I made the requested changed with commit https://github.com/sef-global/scholarx-frontend/pull/146/commits/389e43a5005e686ecbc4225aba9e9731a866ea34. Please review

2021-05-17 11:10 UTC, Gravewalker666 requested changes

2021-05-17 11:10 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/MenteeQuestions/components/AddQuestions/index.tsx
> +import styles from '../../.././styles.css';
let's change the import order to have `react`, `react-router` and `axios` first and then `antd`. Keep the others as it is.

2021-05-17 11:10 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/MenteeQuestions/components/EditQuestions/index.tsx
> +import { Question } from '../../../../../../interfaces';
same thing here as well.

2021-05-17 11:26 UTC, YaiyaSam commented on src/scenes/Dashboard/scenes/MenteeQuestions/components/EditQuestions/index.tsx
> +import { Question } from '../../../../../../interfaces';
Resolved with commit 8a582f0e4b13788122c7c49488be70fd5ed15221 Please review 😊

2021-05-17 11:36 UTC, anjula-sack approved these changes
Good job! @YaiyaSam

2021-05-17 11:46 UTC, Gravewalker666 approved these changes
Thank you @YaiyaSam 
Great work

2021-05-17 11:47 UTC, merged