Use a ant drawer to show the mentor application
sef-global/scholarx-frontend-v1 pull request #156
Opened 2021-05-22 09:19 UTC by anjula-sack

## Purpose

- The purpose of this PR is to fix #147 

## Goals

- The admin should be able to view the mentor application

## Approach

- Added a drawer
- Added the mentee responses

## Screenshots

![image](https://user-images.githubusercontent.com/43912578/119221349-8b89d600-bb0c-11eb-92a8-ed30ef06349a.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-05-22 09:38 UTC, Gravewalker666 requested changes

2021-05-22 09:38 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorRow/index.tsx
> +import { MentorResponse, Props } from './interfaces';
Let's change the import order to what we discussed the other day on slack

2021-05-22 09:41 UTC, Gravewalker666 commented
@anjula-sack 
can we move this part over here and make the question text a bit smaller 
![image](https://user-images.githubusercontent.com/45477334/119222025-f4268200-bb0f-11eb-8cd9-8037275d1d7f.png)

2021-05-22 11:48 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorRow/index.tsx
> +import { MentorResponse, Props } from './interfaces';
fixed

2021-05-23 07:22 UTC, Gravewalker666 approved these changes
Thank you @anjula-sack

2021-05-23 07:23 UTC, merged