Update the mentee apply page content
sef-global/scholarx-frontend-v1 pull request #160
Opened 2021-05-25 18:33 UTC by kumuditha-udayanga

## Purpose

The purpose of this PR is to fix #157

## Goals

- Update the description and add a new button to download the template in the mentee application.

## Approach

- Create a new constant to the application link in `constants.ts`.
- Change the description in the mentee application
- Add a new button to the mentee application and link to the newly created constant.

## Screenshots

![Kapture 2021-05-25 at 23 59 13](https://user-images.githubusercontent.com/27630091/119550084-93b86e80-bdb5-11eb-90e0-3c846b1d2617.gif)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
- OS: macOS BigSur
- IDEA: IntelliJ
- Browser: Safari

2021-05-25 18:40 UTC, Gravewalker666 requested changes

2021-05-25 18:40 UTC, Gravewalker666 commented on src/scenes/Home/scenes/RequestMentors/scenes/MenteeApplication/index.tsx
> +                      </Button>
Shall we make this link open in a new tab?

2021-05-25 20:04 UTC, anjula-sack requested changes

2021-05-25 20:04 UTC, anjula-sack commented on src/constants.ts
> +export const APPLICATION_TEMPLATE = 'www.application-template-link.com';
let's add a google doc link right now instead of  changing it later @Gravewalker666

2021-05-26 08:43 UTC, Gravewalker666 commented on src/constants.ts
> +export const APPLICATION_TEMPLATE = 'www.application-template-link.com';
Yeah, we could do that, @jayasanka-sack can you create a doc with the sef email and send a view-only share link to kumuditha?

2021-05-26 13:36 UTC, kumuditha-udayanga commented
PR is been updated, please review :), @anjula-sack @Gravewalker666

2021-05-26 13:56 UTC, anjula-sack approved these changes
Thank you! @kumuditha-udayanga

2021-05-26 14:22 UTC, Gravewalker666 approved these changes
Great Job @kumuditha-udayanga

2021-05-26 14:23 UTC, merged