Create add programme, edit programme, manage mentees, manage mentors …
sef-global/scholarx-frontend-v1 pull request #17
Opened 2020-10-17 09:38 UTC by miluckshan-j

…view

## Purpose
The purpose of this PR is to fix #4 #7 #8 #9 

## Goals
Can add a new programme
Can edit existing programme
Manage mentors
Manage mentees

## Approach
Used ant design components

## Screenshots
Add button
![Screenshot_20201017_150052](https://user-images.githubusercontent.com/52714282/96333863-10e66d00-108a-11eb-91ab-31cd59675e23.png)

Modal pops up 
![Screenshot_20201017_150058](https://user-images.githubusercontent.com/52714282/96333872-252a6a00-108a-11eb-8aa4-ed94f2ab5437.png)

Edit programme
![Screenshot_20201017_150114](https://user-images.githubusercontent.com/52714282/96333883-35dae000-108a-11eb-8e62-d7783a80d624.png)

Mentor management with pagination
![Screenshot_20201017_150121](https://user-images.githubusercontent.com/52714282/96333887-3ffcde80-108a-11eb-8726-efcf0883e1ce.png)

Mentee management with pagination
![Screenshot_20201017_150128](https://user-images.githubusercontent.com/52714282/96333910-5f940700-108a-11eb-8401-d3c3de4daa52.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
@anjula-sack's #14 

## Test environment
Kubuntu 16.04
Chromium Browser

## Learning
https://ant.design/components/form/
https://ant.design/components/list/

2020-10-17 11:01 UTC, anjula-sack requested changes

2020-10-17 11:01 UTC, anjula-sack commented on src/scenes/Home/index.tsx
> +                    style={addBtn}
It's better to use external css

2020-10-17 11:05 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentees/index.tsx
> +export default ManageMentees;
End of line

2020-10-17 11:09 UTC, anjula-sack commented on src/index.tsx
> +
Remove this extra line

2020-10-17 11:20 UTC, miluckshan-j commented on src/scenes/Home/index.tsx
> +                    style={addBtn}
Sure. Thanks!

2020-10-17 11:34 UTC, miluckshan-j commented on src/index.tsx
> +
Will work on it.

2020-10-17 11:45 UTC, anjula-sack requested changes

2020-10-17 11:45 UTC, anjula-sack commented on src/scenes/Home/styles.css
> +}
End of Line :)

2020-10-18 04:21 UTC, jayasanka-sack requested changes
Thanks @miluckshan-j ,

I've requested some minor edits.

2020-10-18 04:21 UTC, jayasanka-sack commented on src/scenes/Dashboard/components/PersonCard/index.tsx
> +function PersonCard(props) {
As we discussed, we don't need a component for PersonCard because it changes according to the place where it is. Let's move the list item to the parent component instead of creating a new component. 

https://github.com/sef-global/scholarx-frontend/pull/14#issuecomment-703475623

2020-10-18 04:21 UTC, jayasanka-sack commented on src/scenes/Home/components/AddProgrammeModal/index.tsx
> +function AddProgrammeModal(props) {
We can move the Add button to this component and maintain the visible state here.

2020-10-18 04:21 UTC, jayasanka-sack commented on src/scenes/Home/index.tsx
> +              </Col>
Move this to the Add program model and maintain the `visible` state there. (since it is a boolean the variable name should start with something like 'is' or 'has' )

2020-10-18 06:13 UTC, miluckshan-j commented on src/scenes/Dashboard/components/PersonCard/index.tsx
> +function PersonCard(props) {
Thanks. Will look into it.

2020-10-18 06:13 UTC, miluckshan-j commented on src/scenes/Home/components/AddProgrammeModal/index.tsx
> +function AddProgrammeModal(props) {
Noted.

2020-10-18 06:17 UTC, miluckshan-j commented on src/scenes/Home/index.tsx
> +              </Col>
Working on it. Thanks.

2020-10-19 13:16 UTC, jayasanka-sack approved these changes
Thanks @miluckshan-j !

2020-10-19 13:16 UTC, merged