Prevent admins from adding questions during/after MENTOR_APPLICATION …
sef-global/scholarx-frontend-v1 pull request #178
Opened 2021-06-07 17:03 UTC by Piumal1999

…period

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-06-08 05:04 UTC, Gravewalker666 requested changes
Woah this is very impressive @Piumal1999 

But I think instead of putting the logic here inside the component we can move this method up the hierarchy into `MentorQuestions/index.tsx` and conditionally render this component and the edit/add button right there itself. 

 If we do it like this we'll have to call this endpoint once again in the `EditQuestions` component and do the whole conditional rendering thing there too.

2021-06-09 03:27 UTC, anjula-sack requested changes
Good job! @Piumal1999

2021-06-09 03:27 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/MentorQuestions/components/AddQuestions/index.tsx
> +  const [isValidProgramState, setIsValidProgramState] = useState<boolean>(true);
`isValidProgramState` -> `isProgramStateValid` makes more sense right?

2021-06-09 09:45 UTC, Piumal1999 commented on src/scenes/Dashboard/scenes/MentorQuestions/components/AddQuestions/index.tsx
> +  const [isValidProgramState, setIsValidProgramState] = useState<boolean>(true);
Yeah, that's right. I updated it

2021-06-09 09:48 UTC, Piumal1999 commented
> Woah this is very impressive @Piumal1999
> 
> But I think instead of putting the logic here inside the component we can move this method up the hierarchy into `MentorQuestions/index.tsx` and conditionally render this component and the edit/add button right there itself.
> 
> If we do it like this we'll have to call this endpoint once again in the `EditQuestions` component and do the whole conditional rendering thing there too.

Yeah, I updated the PR according to your suggestion. Thanks!

2021-06-09 09:55 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/MentorQuestions/components/AddQuestions/index.tsx
> +function AddQuestions(props: { isProgramStateValid: boolean }) {
can you create an interface?
```
interface AddQuestionsProps {
     isProgramStateValid: boolean
}
```
after that you can use it like this,
`AddQuestions({ isProgramStateValid }:AddQuestionsProps)`

2021-06-09 09:58 UTC, anjula-sack requested changes

2021-06-09 09:58 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/MentorQuestions/components/AddQuestions/index.tsx
> +      {props.isProgramStateValid && (
Once you created that interface you use it like this,
`props.isProgramStateValid `-> `isProgramStateValid`

2021-06-09 10:10 UTC, Piumal1999 commented on src/scenes/Dashboard/scenes/MentorQuestions/components/AddQuestions/index.tsx
> +function AddQuestions(props: { isProgramStateValid: boolean }) {
Ah right. Updated

2021-06-09 10:10 UTC, Piumal1999 commented on src/scenes/Dashboard/scenes/MentorQuestions/components/AddQuestions/index.tsx
> +      {props.isProgramStateValid && (
Updated. Thanks

2021-06-09 10:14 UTC, anjula-sack approved these changes
Awesome! @Piumal1999

2021-06-12 14:10 UTC, Gravewalker666 approved these changes
Good job @Piumal1999

2021-06-12 14:10 UTC, merged