Create view for mentor application
sef-global/scholarx-frontend-v1 pull request #22
Opened 2020-10-20 23:54 UTC by Gimhan-minion

## Purpose
The purpose of this PR is to fix #16

## Goals
- To create a view for mentor Application

## Approach
- Used antd Steps component to create separate sections

## Screenshots
![Screencast from 10-21-2020 05_08_24 AM](https://user-images.githubusercontent.com/60275681/96656265-116a5680-135d-11eb-9206-e308028e7ec5.gif)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-10-21 05:01 UTC, Gravewalker666 requested changes, later dismissed
Great work dude, requested some minor changes. Please look into it.

2020-10-21 05:01 UTC, Gravewalker666 commented on src/scenes/Home/components/MentorApplication/index.tsx
> +  };
Let's lose all the `console.logs`

2020-10-21 12:49 UTC, jayasanka-sack requested changes
Thanks @Gimhan-minion !
I've added some comments

2020-10-21 12:49 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/index.tsx
> +    setCurrent(current + 1);
```suggestion
    setCurrent(2);
```
We know that the next step's number is `2`. Therefore no need to do calculations.

2020-10-21 12:49 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/index.tsx
> +  const selectGo = () => {
The function name should reflect what the function does. 

Here's a great inspiration.
https://dmitripavlutin.com/coding-like-shakespeare-practical-function-naming-conventions/

2020-10-21 12:49 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/index.tsx
> +  const [current, setCurrent] = useState<number>(0);
change the variable name `current ` to something descriptive. ex: `currentStep`

2020-10-21 12:49 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/index.tsx
> +          </Row>
No need for this step at the moment.

2020-10-21 12:49 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/styles.css
> +.customButtonNext{
```suggestion
.nextButton{
```

2020-10-21 12:49 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/index.tsx
> +                  <b>Q2.</b>Why did you apply for ScholarX?
The second step is to add the instructions for the mentees.

2020-10-21 12:51 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/index.tsx
> +        )}
There are no 3 questions. 
Let's discuss this at today's meeting.

2020-10-22 11:17 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/styles.css
> +.form{
```suggestion
.form {
```

2020-10-22 11:17 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorApplication/styles.css
> +.container{
```suggestion
.container {
```

2020-10-22 11:28 UTC, Gimhan-minion commented
Changes made @jayasanka-sack

2020-10-22 11:30 UTC, jayasanka-sack approved these changes
Thanks @Gimhan-minion ! 😍

2020-10-22 11:32 UTC, merged