Change the required message in mentor application
sef-global/scholarx-frontend-v1 pull request #231
Opened 2021-08-04 11:27 UTC by anjula-sack

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-08-05 03:27 UTC, Gravewalker666 requested changes

2021-08-05 03:27 UTC, Gravewalker666 commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +                                    message: 'Please answer the question',
shall we change this to something simple like "Required" or something

2021-08-05 03:34 UTC, anjula-sack commented on src/scenes/Home/scenes/EditMentorApplication/index.tsx
> +                                    message: 'Please answer the question',
Done

2021-08-06 11:27 UTC, Gravewalker666 approved these changes
Nice work @anjula-sack

2021-08-06 11:27 UTC, merged