Migrate mentee API calls to mentee-services
sef-global/scholarx-frontend-v1 pull request #234
Opened 2021-08-07 13:57 UTC by NethmiRodrigo

## Purpose
The purpose of this PR is to fix #191 

## Goals
To migrate all mentee related API calls to a separate utility file

## Approach
Removed axios calls related to mentees from all components and moved them to a separate utility file called mentee-services

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Windows 10
Google Chrome

2021-08-07 14:01 UTC, anjula-sack requested changes
Awesome job!

2021-08-07 14:01 UTC, anjula-sack commented on src/scenes/Home/scenes/RequestMentors/scenes/MenteeApplication/index.tsx
> +    console.log(mentee);
Let's remove the console log

2021-08-07 14:01 UTC, anjula-sack commented on src/scenes/Home/scenes/RequestMentors/scenes/MenteeApplication/index.tsx
> +      console.log(response);
Here as well

2021-08-07 14:08 UTC, NethmiRodrigo commented on src/scenes/Home/scenes/RequestMentors/scenes/MenteeApplication/index.tsx
> +    console.log(mentee);
I forgot to remove it sorry😅.

2021-10-03 04:49 UTC, anjula-sack requested changes
Can you resolve the conflicts? @NethmiRodrigo

2021-12-06 09:15 UTC, cmdrGuyson commented
@NethmiRodrigo I think we should close this PR. There have been a lot of changes (specially with my latest PR). Lets do this refactor while wiring the new UIs.

@anjula-sack I think we should make sure all network call logic is inside a service file when approving PRs with business logic

2021-12-07 13:40 UTC, jayasanka-sack commented
> @NethmiRodrigo I think we should close this PR. There have been a lot of changes (specially with my latest PR). Lets do this refactor while wiring the new UIs.
> 
> @anjula-sack I think we should make sure all network call logic is inside a service file when approving PRs with business logic

Agree with @cmdrGuyson's suggestion.

2021-12-07 13:40 UTC, closed without merging