Display mentor details during Mentee application period
sef-global/scholarx-frontend-v1 pull request #278
Opened 2021-12-26 20:08 UTC by Piumal1999

## Purpose

The purpose of this PR is to fix #276 

## Goals

Display mentors and their details publicly during Mentee Application period

## Approach

Replaced dummy data with actual data got from the backend
removed unused variables and methods

## Screenshots

![image](https://user-images.githubusercontent.com/27498587/147418887-7807a954-f6e0-44be-8200-792cca8489e2.png)

![image](https://user-images.githubusercontent.com/27498587/147418918-552fbcd5-f3d3-47e0-bcf2-8de90a7371b7.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
#256

## Test environment
 
MacOs

## Learning

N/A

2021-12-29 01:11 UTC, Gravewalker666 requested changes
Rest of the things looks fine, we could improve the UI afterwards 
Requested some minor changes

2021-12-29 01:11 UTC, Gravewalker666 commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  '/program/' + programId + '/mentor/' + mentor.id + '/view'
```suggestion
                  `/program/${programId}/mentor/${mentor.id}/view`
```

2021-12-29 01:11 UTC, Gravewalker666 commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  '/program/' + programId + '/mentor/' + mentor.id + '/view'
And having an anchor tag would refresh the entire page, We can use ant designs `Link` component to direct the users without refreshing the page

2021-12-29 07:11 UTC, Piumal1999 commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  '/program/' + programId + '/mentor/' + mentor.id + '/view'
Ah right. fixed with a5abb9c

2021-12-29 07:19 UTC, Gravewalker666 commented on src/scenes/Home/scenes/RequestMentors/components/Mentors/index.tsx
> +                  '/program/' + programId + '/mentor/' + mentor.id + '/view'
Nice

2021-12-30 04:48 UTC, Gravewalker666 approved these changes
Good job @Piumal1999

2021-12-30 04:48 UTC, merged