Create UI to update user email
sef-global/scholarx-frontend-v1 pull request #350
Opened 2022-07-09 11:05 UTC by YaiyaSam

## Purpose

The purpose of this PR is to fix #348

## Goals

To create a new ui to update user email

## Approach

Added a new `Settings` page to the navbar of the home page

## Screenshots

![image](https://user-images.githubusercontent.com/72991092/178102946-19a0b373-842b-4992-8e0b-70fa0b2ae892.png)

2022-07-13 16:47 UTC, anjula-sack commented
Good job! @YaiyaSam Can we have different content at the initial login? Like, Confirm Email and just an input? After that, It will be like yours.

2022-07-16 09:16 UTC, YaiyaSam commented
> Good job! @YaiyaSam Can we have different content at the initial login? Like, Confirm Email and just an input? After that, It will be like yours.

sorry just saw this. what i was going to do was...have something similar to the loginmodal to appear on the home page asking if the current email is the one they are using. and if the user select yes, that would just the update the db, if the user selects no, then they would get redirected to this page to update the email.

2022-07-16 14:28 UTC, anjula-sack commented
> > Good job! @YaiyaSam Can we have different content at the initial login? Like, Confirm Email and just an input? After that, It will be like yours.
> 
> sorry just saw this. what I was going to do was...have something similar to the loginmodal to appear on the home page asking if the current email is the one they are using. and if the user select yes, that would just the update the db, if the user selects no, then they would get redirected to this page to update the email. which one should I go with?

I think modal is good cuz we don't have much content to show as well. Your solution is better

2022-07-20 08:06 UTC, anjula-sack requested changes

2022-07-20 08:06 UTC, anjula-sack commented on src/scenes/Home/scenes/Settings/styles.css
> +}
EOL

2022-07-30 03:42 UTC, anjula-sack commented on src/scenes/Home/scenes/Settings/styles.css
> +}
can you add the extra line here? @YaiyaSam

2022-07-30 03:59 UTC, YaiyaSam commented on src/scenes/Home/scenes/Settings/styles.css
> +}
yeah ill add tht

2022-07-30 09:32 UTC, anjula-sack commented on src/components/EmailModal/interfaces.ts
> +  onCancel: () => void | null;
why do we need the `null` type here?

2022-07-30 09:34 UTC, YaiyaSam commented on src/scenes/Home/scenes/Settings/styles.css
> +}
@anjula-sack is this fixed now?

2022-07-30 09:35 UTC, YaiyaSam commented on src/components/EmailModal/interfaces.ts
> +  onCancel: () => void | null;
oh yeah i can get rid of the null for both onCancel and onConfirm ryt

2022-07-30 10:26 UTC, YaiyaSam commented on src/components/EmailModal/interfaces.ts
> +  onCancel: () => void | null;
i removed it. pls review

2022-07-30 14:10 UTC, anjula-sack approved these changes
Thanks for getting this done! @YaiyaSam

2022-07-30 14:10 UTC, merged