Delete mentee function
sef-global/scholarx-frontend-v1 pull request #42
Opened 2020-10-27 05:18 UTC by miluckshan-j

## Purpose
The purpose of this PR is to fix #23 

## Goals
Able to fetch all mentees and delete a particular mentee.

## Approach
Used a dropdown to select options where the user can choose to delete the mentee. A pop up prompts the user to confirm one last time. If successful, it gives a success notification and a error otherwise.

## Screenshots
**Fetch data from API**
![Screenshot_20201017_150128](https://user-images.githubusercontent.com/52714282/97259631-47b64300-1841-11eb-9482-1d5e9a5fe7e5.png)

**Dropdown on hover over 'More'**
![Screenshot_20201027_005650](https://user-images.githubusercontent.com/52714282/97259656-56045f00-1841-11eb-8b0f-dea208b9e8da.png)

**Prompt confirmation**
![Screenshot_20201027_005707](https://user-images.githubusercontent.com/52714282/97259683-64527b00-1841-11eb-8529-b74887f55fb9.png)

**Notification on success**
![Screenshot_20201027_005745](https://user-images.githubusercontent.com/52714282/97259706-7502f100-1841-11eb-8d6f-fb2da2d34c97.png)

**Notification on error**
![Screenshot_20201027_005713](https://user-images.githubusercontent.com/52714282/97259730-821fe000-1841-11eb-8478-2b8c9cdbd21b.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Kubuntu 16.04
Chromium 85.0.4183.121

## Learning
https://ant.design/components/dropdown
https://ant.design/components/notification
https://ant.design/components/modal

2020-10-27 06:06 UTC, jayasanka-sack requested changes
Great work @miluckshan-j !

I added some comments. 
Apart from that, the following things should be fixed.
1. As per the requirement this functionality is only available after the mentor approval lifecycle state. you don't need to add lifecycle state codes here but at that stage, the only available option for admin is removing a mentor. Therefore, no need for a dropdown; adding a button would be sufficient.
2. Let's rename the option as "Remove" not "Delete"

2020-10-27 06:06 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +  function confirmDelete() {
Add an arrow function here. 

And change the function name

2020-10-27 06:06 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +              notification.warning({
just throw an error the catch block will catch it

2020-10-27 06:06 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +            notification.warning({
let's make this an error

2020-10-27 07:00 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentees/interfaces.tsx
> +  id: number;
Use the Profile interface

2020-10-27 10:31 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +  function confirmDelete() {
Sure. Will make the changes.

2020-10-27 10:31 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +              notification.warning({
Noted

2020-10-27 10:31 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +            notification.warning({
Alright but won't a notification make sense too?

2020-10-27 10:32 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/interfaces.tsx
> +  id: number;
Thanks for pointing out.

2020-10-27 13:04 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +            notification.warning({
It should be notification.error

2020-10-28 06:17 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +  function confirmDelete() {
@jayasanka-sack used a delete button and removed the view button since it's redundant. It already goes to the URL when you click the name.

![Screenshot_20201028_114116](https://user-images.githubusercontent.com/52714282/97399447-35a4d500-1913-11eb-9c68-8d726bee1c87.png)

2020-10-28 12:13 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/components/ListAction/index.tsx
> +      },
Seems we don't need this event

2020-10-28 12:14 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/components/ListAction/index.tsx
> +  const confirmRemoveMentee = () => {
how about `removeMentee`?

2020-10-28 12:16 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentees/index.tsx
> +                <ListAction key={item.profile.id} id={item.profile.id} />,
Shall we move the code to this component instead of creating a new?

2020-10-30 17:51 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/index.tsx
> +                <ListAction key={item.profile.id} id={item.profile.id} />,
Made the changes.

2020-10-30 17:51 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/ListAction/index.tsx
> +  const confirmRemoveMentee = () => {
Sounds good

2020-10-30 17:51 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/ListAction/index.tsx
> +      },
Removed :)

2020-11-02 14:39 UTC, anjula-sack approved these changes
Thank you! @miluckshan-j

2020-11-03 03:35 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentees/components/DropdownItem/index.tsx
> +              notification.warning({
Made all requested changes.

2020-11-03 07:13 UTC, jayasanka-sack approved these changes
Thanks @miluckshan-j !

2020-11-03 07:13 UTC, merged