List all the mentors in a program for mentees
sef-global/scholarx-frontend-v1 pull request #44
Opened 2020-10-30 04:43 UTC by anjula-sack

## Purpose

The purpose of this PR is to fix #43 
## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-11-03 07:15 UTC, jayasanka-sack requested changes

2020-11-03 07:15 UTC, jayasanka-sack commented on src/scenes/Home/scenes/RequestMentors/index.tsx
> +                },
Remove this event listener

2020-11-03 07:15 UTC, jayasanka-sack commented on src/scenes/Home/scenes/RequestMentors/index.tsx
> +                pageSize: 8,
The page size is hard coded here

2020-11-03 07:15 UTC, jayasanka-sack commented on src/scenes/Home/scenes/RequestMentors/index.tsx
> +        notification.warning({
```suggestion
        notification.error({
```

2020-11-06 12:21 UTC, anjula-sack commented on src/scenes/Home/scenes/RequestMentors/index.tsx
> +                pageSize: 8,
pageSIze means no of items per page

2020-11-06 12:24 UTC, anjula-sack commented on src/scenes/Home/scenes/RequestMentors/index.tsx
> +                },
ok

2020-11-06 12:24 UTC, anjula-sack commented on src/scenes/Home/scenes/RequestMentors/index.tsx
> +        notification.warning({
ok

2020-11-09 11:21 UTC, jayasanka-sack approved these changes
Thanks @anjula-sack !

2020-11-09 11:22 UTC, merged