Implemented manage mentors for all states
sef-global/scholarx-frontend-v1 pull request #49
Opened 2020-11-11 13:19 UTC by miluckshan-j

## Purpose
The purpose of this PR is to fix #45.

## Goals
The admins can approve and reject a mentor as well as remove based on state of the program.

## Approach
There are 7 states in a program. The view is different based on the state. 
1) **CREATED** - Since none of the mentors applied, it should be blank.
2) **MENTOR_APPLICATION** - Mentors send in their application and we could remove if it was a spam
3) **MENTOR_SELECTION** - The admins will approve/reject applications based on the program criteria. They could also remove an mentor applicant for other reasons.
4) **MENTEE_APPLICATION** - All approved mentors will wait till the mentees apply for them. We could remove a mentor in this stage too.
5) **MENTEE_SELECTION** - This is similar to the previous view.
6) **ONGOING** - This is similar to the previous view.
7) **COMPLETED** - This view will be blank as there isn't any actions required.

In order to deal with the multiple views and its actions, switch statements were used to render the actions. Actions were generalized wherever possible.

## Screenshots

**CREATED state**
![CREATED](https://user-images.githubusercontent.com/52714282/98815497-3e39f700-244d-11eb-8be7-9f3d38586a49.png)

**MENTOR_APPLICATION state**
![MENTOR_APPLICATION](https://user-images.githubusercontent.com/52714282/98815556-51e55d80-244d-11eb-9fe0-253c05d751ff.png)

**MENTOR_SELECTION state**
![MENTOR_SELECTION](https://user-images.githubusercontent.com/52714282/98815585-5f9ae300-244d-11eb-9681-1ac49f084826.png)

**MENTEE_APPLICATION, MENTEE_SELECTION & ONGOING state**
![ONGOING](https://user-images.githubusercontent.com/52714282/98815646-7e00de80-244d-11eb-94c7-40c442a9d5a2.png)

**COMPLETED state**
![COMPLETED](https://user-images.githubusercontent.com/52714282/98815690-8d802780-244d-11eb-9b99-d68cf086315f.png)

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Kubuntu 16.04
Chromium 85.0.4183.121

2020-11-11 14:07 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +        console.log(`Approved ${props.id}`);
Remove this console log

2020-11-12 02:02 UTC, Gravewalker666 requested changes
This is brilliant dude, really appreciate the effort and the robustness of code is over the top.
Great job @miluckshan-j. 
There were some minor issues, trivial stuff like `logs`. I stated 'em all below. Can you check 'em again and update the code?

2020-11-12 02:02 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      })
I think we should set is loading to false after the 21st line.

2020-11-12 02:04 UTC, Gravewalker666 requested changes

2020-11-12 02:04 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +    });
Oops another one

2020-11-12 02:04 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +    });
Let's remove this log :)

2020-11-12 02:09 UTC, Gravewalker666 commented
Oh, and another thing, let's change the title of the PR and commit message to something like 'Implement' instead of putting 'Implemented'. 
Your Pr and commit messages should be kind of in the narrative of, "Merge this PR/Commit to 'Implement Bla blah blah function'"

2020-11-13 04:00 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +        console.log(`Approved ${props.id}`);
Alright, will do :)

2020-11-13 04:01 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      })
Thank you @Gravewalker666! Logs were for my debugging purposes. Will remove the all. :)

2020-11-13 04:01 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +    });
Noted

2020-11-13 04:02 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +    });
Sure.

2020-11-13 04:03 UTC, miluckshan-j commented
> Oh, and another thing, let's change the title of the PR and commit message to something like 'Implement' instead of putting 'Implemented'.
> Your Pr and commit messages should be kind of in the narrative of, "Merge this PR/Commit to 'Implement Bla blah blah function'"

Noted. Will follow them in the future.

2020-11-13 17:20 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          });
Move this to another function to increase the readerbility

2020-11-13 17:22 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      break;
We don't need this to break right?

2020-11-14 05:09 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      break;
Yeah, Not compulsory.

2020-11-14 05:12 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          });
Makes sense. Will do.

2020-11-14 05:21 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      })
By the way, loading is set to false after the mentor list is loaded. It's in line 41. Would it be a necessity to put in 21?

2020-11-14 06:28 UTC, Gravewalker666 approved these changes

2020-11-14 06:28 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      })
Oh, I didn't see that part, then it's fine.

2020-11-14 06:39 UTC, Gravewalker666 requested changes

2020-11-14 06:39 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const rejectMentorApi = () => {
`rejectMentorApi`, I don't know how to feel about this naming convention, I'd rather prefer a name that describes an action for a function. But we already have a method called `rejectMentor` ryt? What do we do? Shall we put something like `postRejectMentor`, that's just off the top o ma head, can you think of a better one?

2020-11-14 06:39 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const approveMentorApi = () => {
Same name convention thing here as well

2020-11-14 06:45 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const approveMentorApi = () => {
Better to covert it to a verb

2020-11-14 06:47 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +function RemoveMentor(props) {
Missing data type of props

2020-11-14 06:53 UTC, jayasanka-sack requested changes

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +      .then((result: any) => {
Avoid using `any` unless you don’t have any other options.

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +  const removeMentor = (id) => {
Add data type

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  let actions;
Add data type

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const approveMentor = (id) => {
Data type

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +      .then((result: any) => {
Add data type

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +      .then((result: any) => {
Add data type

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +function MentorActions(props) {
Add data type

2020-11-14 06:53 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          });
This should rerender the component to enable or disable buttons right?

2020-11-14 07:16 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const rejectMentorApi = () => {
Alright. `postRejectMentor` sounds good too. I'm really sorry. Not great with naming :sweat_smile:

2020-11-14 07:17 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const approveMentorApi = () => {
Alright.

2020-11-14 07:17 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  const approveMentorApi = () => {
Planning to go with `postApproveMentor`. Hope that's fine.

2020-11-14 07:18 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +function RemoveMentor(props) {
Will look into it. Thanks for pointing it out.

2020-11-14 07:18 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +      .then((result: any) => {
Yeah. Sure!

2020-11-14 07:19 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +  const removeMentor = (id) => {
Noted.

2020-11-14 07:24 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          });
Yeah. Better to put it in a function and call it, right?

2020-11-15 02:35 UTC, Gravewalker666 requested changes

2020-11-15 02:35 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  };
The parameter id is unused, `postRejectMentor` function uses the id taken directly from the props to send the API request. I think it's not necessary to pass the id to this function.
Is there a specific reason? If not let's remove em :)

2020-11-15 02:35 UTC, Gravewalker666 commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +  };
Same issue here :)

2020-11-16 04:39 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +  };
No particular reason, will remove it. Thanks for pointing it out.

2020-11-16 04:39 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +  };
Noted

2020-11-18 01:11 UTC, Gravewalker666 approved these changes, later dismissed
Good job @miluckshan-j 
There are still some reviews left by @jayasanka-sack will you see to that too?

2020-11-18 13:20 UTC, jayasanka-sack requested changes

2020-11-18 13:20 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          message: 'Warning!',
notification.warning -> notification.error

Applied to all other API calls.
Change the message too.

2020-11-18 13:20 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +            'Something went wrong when fetching the programme detail',
This is a very minor request. Let's use `program` because everywhere else it has been used like that.

2020-11-18 13:20 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      .then((result: any) => {
Let's try to avoid using `any` unless we don't have another option

2020-11-18 13:20 UTC, jayasanka-sack commented
Let's have a code review on this today

2020-11-21 12:33 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          });
Seems this isn't implemented yet

2020-11-21 12:49 UTC, jayasanka-sack requested changes
Good job @miluckshan-j !

I've added some comments

2020-11-21 12:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +    }
How about passing the string (the exact state) instead of a number?

2020-11-21 12:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          disabled
I think this whole if blocks can be simplified by using two booleans. (for the enable/disable states of the buttons)

2020-11-21 12:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +          description: 'Something went wrong when updating state',
notification.error

change the message too. (It's not a warning, but error)

2020-11-21 12:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +type Props = { id: number, state: string, loadMentors: () => void };
```suggestion
type Props = { id: number, state: string, onChange: () => void };
```

2020-11-21 12:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +              loadMentors={loadMentors}
```suggestion
              onChange={loadMentors}
```

2020-11-21 12:49 UTC, jayasanka-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +  }
This can be replaced. with something like this
```
let mentorView: ReactNode;

if(programState === 'CREATED' || programState === 'REMOVED'){
    mentorView = displayEmpty;
} else {
    mentorView = displayMentors;
}
```

2020-11-21 18:05 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +    }
Sounds good.

2020-11-21 18:05 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +          disabled
Yeah, made it simpler

2020-11-21 18:05 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/components/RemoveMentor/index.tsx
> +          description: 'Something went wrong when updating state',
Noted

2020-11-21 18:06 UTC, miluckshan-j commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +  }
Alright. Changed.

2020-11-22 04:06 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentors/components/MentorActions/index.tsx
> +        enrolmentState: `${mentorState}`,
Add `{ withCredentials: true }` for API call
Ex: .put('http://localhost:8080/admin/mentors/${props.id}/state', {
        enrolmentState: '${mentorState}'},{ withCredentials: true })

2020-11-22 04:09 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +        if (result.status == 200) {
You need to setIsLoading(false) here

2020-11-22 04:10 UTC, anjula-sack commented on src/scenes/Dashboard/scenes/ManageMentors/index.tsx
> +      .get(`http://localhost:8080/programs/${programId}/mentors`)
Add `{ withCredentials: true }` configuration

2020-11-23 06:06 UTC, jayasanka-sack approved these changes
Thanks @miluckshan-j and @Gravewalker666 !!

2020-11-23 06:06 UTC, jayasanka-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +function AllPrograms() {
Delete this file. We don't need it now

2020-11-23 06:07 UTC, merged