Manage mentees of a mentor for all lifecycle states
sef-global/scholarx-frontend-v1 pull request #51
Opened 2020-11-16 07:27 UTC by Gimhan-minion

## Purpose
The purpose of this PR is to fix #48 

## Goals
- To create a view for mentors to handle their mentees for all life cycle states

## Approach
There are 7 states in a program. The view is different based on the state.

1. CREATED - Since none of the mentees applied, it should be blank.
2. MENTOR_APPLICATION - Since none of the mentees applied, it should be blank.
3. MENTOR_SELECTION - Since none of the mentees applied, it should be blank.
4. MENTEE_APPLICATION - All approved mentors will be able to see the mentees who have applied for him.
5. MENTEE_SELECTION - The mentor gets 2 options at this stage. Either approve or reject.
6. ONGOING - This is similar to the 4th view
7. COMPLETED - This view will be blank as there aren't any actions required.
In order to deal with the multiple views and their actions, switch statements were used to render the actions.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-11-16 14:23 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +          message: 'Warning!',
Display the error message instead of saying Warning!

2020-11-16 14:24 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +          message: 'Warning!',
same goes for here

2020-11-16 14:27 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-MenteeSelection/index.tsx
> +            description: 'Successfully updated the mentee state',
Let's change the description to something like  "Successfully approved the mentee" of something like that

2020-11-16 14:28 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-MenteeSelection/index.tsx
> +          description: 'Something went wrong when updating state',
Let's change this one also because Mentor doesn’t have an idea about this state thing.

2020-11-16 14:29 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +          description: 'Something went wrong when fetching the mentors',
It's mentees

2020-11-16 14:30 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +  const { programId } = useParams();
you can use this like this. `const { mentorId, programId } = useParams();`

2020-11-16 14:31 UTC, anjula-sack commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +              console.log(page);
Let's remove this console log

2020-11-18 13:36 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +          message: 'Warning!',
Done!

2020-11-18 13:36 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +          message: 'Warning!',
Noted

2020-11-18 13:36 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-MenteeSelection/index.tsx
> +            description: 'Successfully updated the mentee state',
Yeah sure it makes much sense

2020-11-18 13:36 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-MenteeSelection/index.tsx
> +          description: 'Something went wrong when updating state',
Noted

2020-11-18 13:37 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +          description: 'Something went wrong when fetching the mentors',
My bad :) Fixed that too !

2020-11-18 13:37 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +  const { programId } = useParams();
Yeah sure

2020-11-18 13:37 UTC, Gimhan-minion commented on src/scenes/Home/scenes/Mentor-ManageMentees/index.tsx
> +              console.log(page);
Done

2020-11-22 02:40 UTC, Gravewalker666 approved these changes, later dismissed
Brilliant work, code is super clean, good one @Gimhan-minion

2020-11-22 03:50 UTC, anjula-sack requested changes

2020-11-22 03:50 UTC, anjula-sack commented on src/interfaces.ts
> +  profile: {
Use `Profile` interface instead of this.

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +      .get(`http://localhost:8080/api/scholarx/programs/${programId}`)
You need to add `('API endpoint', { withCredentials: true})` for every API call.
Ex: `.get('http://localhost:8080/api/scholarx/programs/${programId}', { withCredentials: true})`

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +  const getProgram = () => {
Move this to `useEffect()` without creating another variable.

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +    axios
`setIsLoading(true);` right here before calling the API

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
```suggestion
            {program && !shouldLoadMentees && (
```
Try this, I think it should work

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +      .get(`http://localhost:8080/mentors/${mentorId}/mentees`)
Add `{ withCredentials: true }` for API call

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    let successMessage = '';
Add the data type for this

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    let successMessage = '';
```suggestion
    let successMessage: string, successMessage: string  = '';
```

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +      .put(`http://localhost:8080/mentees/${props.mentee.id}/state`, {
`setIsLoading(true)` and later set it to false

2020-11-22 03:50 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    const isApproveDisabled = menteeState == 'APPROVED';
Add the data type

2020-11-22 04:27 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    const isApproveDisabled = menteeState == 'APPROVED';
The data type is automatically defined when we assign a value at variable initialization.

2020-11-22 04:28 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +  const getProgram = () => {
I think it's good to have a new function instead of writing axios calls in the useEffect. It makes the code cleaner. WDYT?

2020-11-22 04:29 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +      .get(`http://localhost:8080/api/scholarx/programs/${programId}`)
Oh yeah, that's true. Also, @Gimhan-minion remove this `/api/scholarx` part

2020-11-22 04:31 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +    axios
It has been already set on line 19. 
This approach has been taken because there are two API calls which get calls one after

2020-11-22 04:34 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
In this case, we know the possible values for the program variable is only `null` OR a `SavedProgram`

`{program && ...` checks whether the program is

- null
- undefined
- NaN
- empty string ("")
- 0
- false

2020-11-22 05:01 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +    axios
so in line 34 if we don't need to load mentees it should be false right?

2020-11-22 05:03 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +    axios
oh yes

2020-11-22 05:06 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
Is it going to check all of them? because we already initiated `program` as null or saved program why would it check for other types?

2020-11-22 05:07 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
It is going to check all of them according to the JS. (Typescript isn't available at runtime )

2020-11-22 05:17 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
So in the compiling stage `Program` is can be null or SavedProgram but when it's in runtime it can be anything right because it's Js?

2020-11-22 05:25 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
No, it can't be, because according to our logic we know the possible values are only null or an object (saved program) Not because we initialized them as that way, but we know all the possible things can be happened according to the written code.  

But, the browser (DOM) does not know that. From this piece of code `{program && ...` we instruct the DOM to check whether the program variable does not equal one of the following,
- null
- undefined
- NaN
- empty string ("")
- 0
- false 

It has to check one by one. 

---
Let's assume the `program`'s value is a program object,

Now, it checks whether it is null. the answer is false.
Then it checks whether it is undefined.  the answer is false.
Then, checks whether it is NaN
then, empty string 
then 0,
then false, 
it is not equal to anything. finally, it say's "hey program, you are good to go!"

2020-11-22 05:29 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
ah okay Thanks for the explanation!

2020-11-22 05:32 UTC, jayasanka-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
Actually, I used the above example only to explain the situation. The actual thing that happens is by the abstract operation `ToBoolean`

For boolean values `ToBoolean` doesn't do any conversion

2020-11-22 05:42 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
ok cool

2020-11-22 07:57 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    let successMessage = '';
@anjula-sack The data type string was automatically removed by eslint

2020-11-22 08:14 UTC, Gimhan-minion commented on src/interfaces.ts
> +  profile: {
Noted!

2020-11-22 08:14 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +      .get(`http://localhost:8080/api/scholarx/programs/${programId}`)
Done :)

2020-11-22 08:15 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +  const getProgram = () => {
I think it better to keep it separate.

2020-11-22 08:15 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +    axios
Done :)

2020-11-22 08:15 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/index.tsx
> +            {!shouldLoadMentees && program != null && (
:)

2020-11-22 08:16 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    let successMessage = '';
Fixed it too

2020-11-22 08:16 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +      .put(`http://localhost:8080/mentees/${props.mentee.id}/state`, {
`setIsLoading(true)` is not defined in MenteeRow

2020-11-22 08:17 UTC, Gimhan-minion commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +    const isApproveDisabled = menteeState == 'APPROVED';
eslint ignores this too

2020-11-22 08:29 UTC, anjula-sack commented on src/scenes/Home/scenes/ManageMentees/components/MenteeRow/index.tsx
> +      errorMessage = '';
`errorMessage: string`

2020-11-22 12:42 UTC, jayasanka-sack approved these changes
Thanks, @Gimhan-minion !

2020-11-22 12:43 UTC, anjula-sack approved these changes
Good job! 👏  @Gimhan-minion

2020-11-22 12:43 UTC, merged