Implementing the dynamic home page based on user
sef-global/scholarx-frontend-v1 pull request #53
Opened 2020-11-18 12:54 UTC by anjula-sack

## Purpose

The purpose of this PR is to fix #52 

## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-11-21 12:28 UTC, jayasanka-sack requested changes
This is very impressive @anjula-sack !!

I added a few minor comments

2020-11-21 12:28 UTC, jayasanka-sack commented on src/index.tsx
> +      .get('http://localhost:8080/me', { withCredentials: true })
`{ withCredentials: true }` is needed for every other API because now it uses the profile cookie

2020-11-21 12:28 UTC, jayasanka-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +  return (
add a space

2020-11-21 12:28 UTC, jayasanka-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +              <p>{program.headline}</p>
Let's use typography's paragraph

2020-11-21 12:28 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorPrograms/index.tsx
> +    axios
we don't need this because it's already in the context.

2020-11-21 12:55 UTC, jayasanka-sack requested changes

2020-11-21 12:55 UTC, jayasanka-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +function AllPrograms(props: { isUserAdmin: boolean }) {
We don't need this prop because it's already in the context, right?

2020-11-21 12:56 UTC, jayasanka-sack commented on src/scenes/Home/components/MentorPrograms/index.tsx
> +    axios
sorry, My bad

2020-11-21 12:56 UTC, anjula-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +function AllPrograms(props: { isUserAdmin: boolean }) {
ah yes

2020-11-22 04:45 UTC, jayasanka-sack requested changes

2020-11-22 04:45 UTC, jayasanka-sack commented on src/scenes/Home/index.tsx
> +            <TabPane tab="All Programs" key="1">
add meaningful key names

2020-11-22 04:45 UTC, jayasanka-sack commented on src/scenes/Home/index.tsx
> +            {user && user.type == 'ADMIN' ? (
```suggestion
            {user != null && user.type == 'ADMIN' ? (
```

2020-11-22 04:45 UTC, jayasanka-sack commented on src/scenes/Home/index.tsx
> +                <TabPane tab="My mentoring programs" key="2">
Change the tab's label. 

Programs I mentor
same applied to the other tab

2020-11-22 04:45 UTC, jayasanka-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +                  <h3>
Let's avoid using `<h1> , <h2> ..., <p>` tags. We can use the Typography components

2020-11-22 05:43 UTC, anjula-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +                  <h3>
yeah sure, BTW this was an already created card, I didn’t create this

2020-11-22 05:44 UTC, anjula-sack commented on src/scenes/Home/index.tsx
> +            <TabPane tab="All Programs" key="1">
sure

2020-11-22 05:45 UTC, jayasanka-sack commented on src/scenes/Home/components/AllPrograms/index.tsx
> +                  <h3>
Yeah, I get you. But we have to fix it somewhere. (otherwise, it's going to get multiplied with the time. Previously there was 1 card with an error. Now it's 3.)

2020-11-22 05:47 UTC, jayasanka-sack approved these changes
Thanks @anjula-sack !

2020-11-22 05:48 UTC, merged