Implement the mentor selection UI
sef-global/scholarx-frontend-v1 pull request #63
Opened 2020-12-19 05:48 UTC by anjula-sack

## Purpose

The purpose of this PR is to fix #61 
## Goals

## Approach

## Screenshots

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-12-21 05:32 UTC, Gravewalker666 requested changes
Amazing work dude, Truly beautiful.
A small issue here though, it shows `my mentor` button even when nobody's signed in.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/102742768-bdd7b180-437b-11eb-9ab8-dd58049da296.png">
Can you change that to something else? As we had in the initial wireframes.

2020-12-21 08:19 UTC, Gimhan-minion commented on src/scenes/Home/components/ActivePrograms/index.tsx
> +                      My mentor
How about using a term like 'View mentors' or just 'Mentors' instead of 'My mentor'. WDYT?

2020-12-21 08:19 UTC, Gimhan-minion commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const getMentors = () => {
how about using `getApprovedMentors` instead of using `getMentors`. WDYT?

2020-12-21 08:39 UTC, anjula-sack commented on src/scenes/Home/components/ActivePrograms/index.tsx
> +                      My mentor
I don't think view mentors is going to work because the purpose of this view is not showing mentors. There are four scenarios. 
1. Have more than one mentor
2. Have only one mentor
3. Haven't selected by a mentor
4.Havenot applied as a mentee

Only in scenario 1, we are going to have more than one mentor.

2020-12-21 08:39 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const getMentors = () => {
yeah, It's great.

2020-12-21 08:42 UTC, Gimhan-minion commented on src/scenes/Home/components/ActivePrograms/index.tsx
> +                      My mentor
Oh! That makes sense. :smiley: Let's leave it as it is.

2020-12-22 05:00 UTC, Gravewalker666 requested changes

2020-12-22 05:00 UTC, Gravewalker666 commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const [isUserApplied, setIsUserApplied] = useState<boolean>(false);
shall we change this var name to `hasUserApplied`?

2020-12-22 05:00 UTC, Gravewalker666 commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  };
Okay in this part what you have done is to first check if this mentee's approved and then if the mentor array is empty check whether the user has applied. But I think it should be the other way around. We should first check if the user has applied and if it is the case we should check and see if he's approved by any. What do you think? @anjula-sack @jayasanka-sack

2020-12-22 05:07 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  };
I think it won’t make a difference but it makes more sense that way

2020-12-22 15:01 UTC, jayasanka-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  };
Yeah I think it's more convenient. +1 for Heshan's suggestion. 

Also, it's better if we could add comments to these logics because status codes aren't self-explanatory with the use case.

2020-12-22 15:03 UTC, jayasanka-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const onMentorIdChange = (e: any) => {
```suggestion
  const handleMentorIdChange = (e: any) => {
```

2020-12-22 15:03 UTC, jayasanka-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const onMentorIdChange = (e: any) => {
Is there a data type for the event? I'm not sure

2020-12-23 03:11 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const [isUserApplied, setIsUserApplied] = useState<boolean>(false);
sure

2020-12-24 04:07 UTC, Gravewalker666 commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const onMentorIdChange = (e: any) => {
I don't think so

2020-12-24 04:09 UTC, Gravewalker666 submitted a review, later dismissed
Great work dude, amazing @anjula-sack 
Look into @jayasanka-sack's comment, so we can get this merged

2020-12-24 12:20 UTC, anjula-sack commented on src/scenes/Home/scenes/MentorConfirmation/index.tsx
> +  const onMentorIdChange = (e: any) => {
No

2020-12-24 14:20 UTC, Gravewalker666 approved these changes
Great!!

2020-12-24 14:22 UTC, Gravewalker666 commented
I checked the flow, and it's working fine. Nothing much to comment on the code seems all good. 
Good work @anjula-sack

2020-12-24 14:22 UTC, merged

2020-12-24 16:17 UTC, jayasanka-sack commented
Thanks @anjula-sack and @Gravewalker666 !